# Generated by Django 4.2.7 on 2024-01-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=255)),
                ('baths', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
